services:
  iti:
    image: iti
    build: .
    ports:
      - "8080:8080"

  postgres:
      image: postgres:14.8-alpine3.18
      environment:
        POSTGRES_DB: "db-data"
        PGDATA: "var/lib/postgresql/data/pgdata"
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"


volumes:
  db-data:
